version: '3.8'

services:
  postgres-db:
    image: postgres:15.3-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - local-network

  app:
    build: .
    container_name: ajudae-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres-db
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
