version: '3.8'

services:
  postgres-db:
    image: postgres:15.3-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    container_name: redis-session
    command: redis-server --requirepass 12345678
    restart: always
    ports:
      - 6380:6379
    volumes:
      - ./data/redis:/data
    networks:
      - local-network

networks:
  default:
    name: local-network
    external: true
